[features]
seeds = false
skip-lint = false
[programs.localnet]
proto = "CzpJ9weBNofFfa3WTr6HGSuAA29citaCXybasQvU8NLD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/clinton/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
